name:                wai-braid
version:             0.1.0.0
github:              "githubuser/wai-braid"
license:             BSD3
author:              "Ghilia Weldesselasie"
maintainer:          "ghiliaweld@gmail.com"
copyright:           "2020 Ghilia Weldesselasie"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wai-braid#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- http-types
- bytestring
- wai-extra
- case-insensitive
- text

library:
  source-dirs: src

tests:
  wai-braid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-braid
    - HUnit
